"""scripts/dev/check_commit_messages.py: forbidden forms, allowed forms and range parsing.

The message checks are pure; the range tests build a throwaway git repository
in a temp directory (nothing touches this repository's history).
"""

import contextlib
import io
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts.dev import check_commit_messages as check  # noqa: E402

BODY = 'Why the change was made.\n\n'


class ForbiddenFormTests(unittest.TestCase):
    def reasons(self, trailer):
        return check.check_message(f'feat: subject\n\n{BODY}{trailer}\n')

    def test_session_trailers_with_a_url_are_rejected(self):
        for trailer in ('Claude-Session: https://claude.ai/code/session_01abc',
                        'claude-session: https://example.com/x',
                        'Codex-Session: http://host/s/1',
                        'Agent-Session: claude.ai/code/session_1'):
            with self.subTest(trailer=trailer):
                self.assertEqual(len(self.reasons(trailer)), 1)
                self.assertIn('session', self.reasons(trailer)[0])

    def test_a_session_trailer_without_a_url_is_flagged_by_name_or_by_id(self):
        for trailer in ('Claude-Session: session_01WeZik6TnLLEfZRKbgPe4Y2',
                        'Agent-Session: session_abc123',
                        'Codex-Session: 7f3a',
                        'Review-Session: session_9'):
            with self.subTest(trailer=trailer):
                self.assertEqual(len(self.reasons(trailer)), 1)
                self.assertIn('session', self.reasons(trailer)[0])

    def test_an_ordinary_session_trailer_is_not_flagged(self):
        self.assertEqual(self.reasons('Review-Session: planning'), [])
        self.assertEqual(self.reasons('Training-Session: onboarding'), [])

    def test_ai_co_authors_are_rejected_by_name_or_email_in_any_case(self):
        for trailer in ('Co-Authored-By: Claude <noreply@anthropic.com>',
                        'Co-authored-by: Claude Sonnet 5.5 <noreply@anthropic.com>',
                        'co-authored-by: someone <bot@ANTHROPIC.COM>',
                        'Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>',
                        'Co-authored-by: ChatGPT <chatgpt@example.com>',
                        'Co-authored-by: OpenAI Codex <codex@openai.com>',
                        'Co-authored-by: Gemini <gemini@google.com>',
                        'Co-authored-by: Cursor Agent <cursor@cursor.com>',
                        'Co-authored-by: Someone <bot@mail.anthropic.com>',
                        'Co-authored-by: Copilot <copilot@github.com>',
                        'Co-authored-by: GitHub Copilot <noreply@example.com>',
                        'Co-authored-by: claude <someone@example.com>',
                        ' Co-authored-by:   Claude Code   <x@example.com>',
                        'Co-authored-by: Claude Opus 4.1 <x@example.com>',
                        'Co-authored-by: Gemini <x@example.com>',
                        'Co-authored-by: Claude 3.5 Sonnet <x@example.com>',
                        'Co-authored-by: Claude Sonnet <x@example.com>',
                        'Co-authored-by: Claude Opus4.1 <x@example.com>',
                        'Co-authored-by: Claude Sonnet4 <x@example.com>',
                        'Co-authored-by: Claude-Opus-4 <x@example.com>',
                        'Co-authored-by: Claude Haiku 4.5 <x@example.com>',
                        'Co-authored-by: Gemini 2.5 Pro <x@example.com>',
                        'Co-authored-by: Gemini Flash <x@example.com>',
                        'Co-authored-by: GPT-4o <x@example.com>',
                        'Co-authored-by: ChatGPT Turbo <x@example.com>'):
            with self.subTest(trailer=trailer):
                reasons = self.reasons(trailer)
                self.assertEqual(len(reasons), 1)
                self.assertIn('AI assistant co-author', reasons[0])

    def test_generated_banners_naming_an_ai_tool_or_url_are_rejected(self):
        for line in ('Generated with [Claude Code](https://claude.ai/code)',
                     '\U0001F916 Generated with Claude Code',
                     'Generated by ChatGPT',
                     'generated by Copilot',
                     'Generated with https://anthropic.com/tool',
                     '  Generated with [Cursor](https://cursor.com)'):
            with self.subTest(line=line):
                reasons = self.reasons(line)
                self.assertEqual(len(reasons), 1)
                self.assertIn('AI generation banner', reasons[0])

    def test_two_problems_are_both_reported(self):
        message = 'fix: x\n\nbody\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nClaude-Session: https://claude.ai/s/1\n'
        self.assertEqual(len(check.check_message(message)), 2)


class AllowedFormTests(unittest.TestCase):
    def test_ordinary_human_co_authors_are_allowed_in_any_case(self):
        for trailer in ('Co-authored-by: Ada Lovelace <ada@example.com>',
                        'co-authored-by: Grace Hopper <grace@navy.example>',
                        'Co-Authored-By: Linus <linus@kernel.example>'):
            with self.subTest(trailer=trailer):
                self.assertEqual(check.check_message(f'feat: x\n\nwhy\n\n{trailer}\n'), [])

    def test_humans_whose_names_or_domains_contain_an_assistant_word_are_allowed(self):
        # Each of these failed when markers were matched as substrings of the whole trailer.
        for trailer in ('Co-authored-by: Claudette Dupont <claudette@example.org>',
                        'Co-authored-by: Claude Monet <cmonet@example.org>',
                        'Co-authored-by: Claude Bernard <claude.bernard@sorbonne.example>',
                        'Co-authored-by: Dana Lee <dana@geminitech.com>',
                        'Co-authored-by: Devin Patel <devin@example.com>',
                        'Co-authored-by: Ada Aiderman <a@example.com>',
                        'Co-authored-by: Pat Rowe <pat@cursorial.org>',
                        'Co-authored-by: Sam Ng <sam@codexlabs.io>',
                        'Co-authored-by: Gemini Rivera <gem@example.com>',
                        'Co-authored-by: Ana Copilotti <ana@example.com>',
                        # A model word that is only the start of a surname is a person.
                        'Co-authored-by: Claude Proctor <human@example.org>',
                        'Co-authored-by: Claude Opusville <human@example.org>',
                        'Co-authored-by: Gemini Haikuson <human@example.org>',
                        'Co-authored-by: Claude Sonnenberg <human@example.org>',
                        'Co-authored-by: Claude Codey <human@example.org>',
                        'Co-authored-by: Claude Codeyville <human@example.org>',
                        'Co-authored-by: Gemini Flashman <human@example.org>',
                        'Co-authored-by: GPT Ultrasound <human@example.org>',
                        'Co-authored-by: Claude Turbotville <human@example.org>',
                        'Co-authored-by: Lee <lee@notanthropic.com>',
                        'Co-authored-by: Lee <lee@openai.com.example.org>'):
            with self.subTest(trailer=trailer):
                self.assertEqual(check.check_message(f'feat: x\n\nwhy\n\n{trailer}\n'), [])

    def test_a_clean_message_passes(self):
        self.assertEqual(check.check_message('feat(studio): load free fonts only on request\n\n'
                                             'Studio no longer contacts Google until the user asks.\n'), [])

    def test_generated_lines_that_name_no_ai_tool_pass(self):
        for line in ('Generated by protoc 25.1', 'Generated with the project formatter',
                     'Generated by Aiderman', 'Generated with cursorial-lint', 'Generated by the Claudette tool',
                     'Generated with devinci-resolve'):
            with self.subTest(line=line):
                self.assertEqual(check.check_message(f'chore: regenerate\n\nwhy\n\n{line}\n'), [])

    def test_a_subject_or_body_that_only_mentions_claude_is_not_a_signature(self):
        self.assertEqual(check.check_message('docs: explain the Claude Desktop setup\n\nSee the Gemini section.\n'), [])

    def test_the_identity_lists_live_in_named_constants(self):
        self.assertIn('anthropic.com', check.AI_DOMAINS)
        self.assertIn('claude', check.AI_NAMES)
        self.assertTrue(check.is_ai_identity('Claude', 'x@example.com'))
        self.assertTrue(check.is_ai_identity('Someone', 'noreply@Anthropic.com'))
        self.assertFalse(check.is_ai_identity('Ada Lovelace', 'ada@example.com'))
        self.assertFalse(check.is_ai_identity('Claude Monet', 'cmonet@example.org'))
        self.assertFalse(check.is_ai_identity('Claude Proctor', 'human@example.org'))
        self.assertTrue(check.is_ai_identity('Claude Opus 4.1', 'human@example.org'))


def git(repo, *args, message=None):
    env = dict(os.environ, GIT_AUTHOR_NAME='A', GIT_AUTHOR_EMAIL='a@example.com',
               GIT_COMMITTER_NAME='A', GIT_COMMITTER_EMAIL='a@example.com')
    return subprocess.run(['git', '-c', 'commit.gpgsign=false', *args], cwd=repo, env=env, check=True,
                          capture_output=True, text=True, input=message).stdout


class RangeTests(unittest.TestCase):
    def setUp(self):
        folder = tempfile.TemporaryDirectory()
        self.addCleanup(folder.cleanup)
        self.repo = Path(folder.name)
        git(self.repo, 'init', '-q', '-b', 'main')

    def commit(self, message):
        git(self.repo, 'commit', '-q', '--allow-empty', '-F', '-', message=message)

    def run_main(self, *argv):
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = check.main(['--repo', str(self.repo), *argv])
        return code, out.getvalue(), err.getvalue()

    def test_a_range_checks_every_commit_in_it_and_nothing_before_it(self):
        self.commit('chore: base\n\nBase commit.\n\nClaude-Session: https://claude.ai/s/old\n')  # outside the range
        git(self.repo, 'branch', 'base')
        self.commit('feat: one\n\nWhy one.\n')
        self.commit('fix: two\n\nWhy two.\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n')
        self.commit('docs: three\n\nWhy three.\n\nCo-authored-by: Ada <ada@example.com>\n')
        self.commit('refactor: four\n\nWhy four.\n\nGenerated with [Claude Code](https://claude.ai/code)\n')
        commits = check.commits_in_range('base..HEAD', self.repo)
        self.assertEqual([c.subject for c in commits], ['refactor: four', 'docs: three', 'fix: two', 'feat: one'])
        code, out, _ = self.run_main('--range', 'base..HEAD')
        self.assertEqual(code, 1)
        lines = out.splitlines()
        fails = [line for line in lines if line.startswith('FAIL ')]
        self.assertEqual(len(fails), 2)
        self.assertRegex(fails[0], r'^FAIL [0-9a-f]{7,} refactor: four: AI generation banner')
        self.assertRegex(fails[1], r'^FAIL [0-9a-f]{7,} fix: two: AI assistant co-author')
        self.assertEqual(lines[-1], 'commit-message check: FAIL: 2 of 4 commits carry agent or process signatures')

    def test_a_clean_range_exits_zero_with_a_one_line_summary(self):
        self.commit('chore: base\n\nBase.\n')
        git(self.repo, 'branch', 'base')
        self.commit('feat: one\n\nWhy.\n\nCo-authored-by: Ada <ada@example.com>\n')
        self.commit('feat: two\n\nWhy.\n')
        code, out, _ = self.run_main('--range', 'base..HEAD')
        self.assertEqual((code, out), (0, 'commit-message check: OK: 2 commits checked\n'))

    def test_without_a_range_only_the_last_commit_is_checked(self):
        self.commit('chore: old\n\nGenerated by ChatGPT\n')
        self.commit('feat: new\n\nWhy.\n')
        code, out, _ = self.run_main()
        self.assertEqual((code, out), (0, 'commit-message check: OK: 1 commit checked\n'))
        self.commit('fix: newest\n\nWhy.\n\nClaude-Session: https://claude.ai/s/1\n')
        self.assertEqual(self.run_main()[0], 1)

    def test_an_all_zero_before_sha_from_a_new_branch_push_means_the_last_commit(self):
        self.commit('feat: one\n\nWhy.\n')
        zeros = '0' * 40
        code, out, _ = self.run_main('--range', f'{zeros}..HEAD')
        self.assertEqual((code, out), (0, 'commit-message check: OK: 1 commit checked\n'))

    def test_merge_commits_are_skipped(self):
        self.commit('chore: base\n\nBase.\n')
        git(self.repo, 'checkout', '-q', '-b', 'topic')
        self.commit('feat: topic\n\nWhy.\n')
        git(self.repo, 'checkout', '-q', 'main')
        self.commit('feat: main\n\nWhy.\n')
        git(self.repo, 'merge', '--no-ff', '-q', 'topic', '-m', 'Merge topic\n\nGenerated with Claude Code')
        commits = check.commits_in_range('HEAD~2..HEAD', self.repo)
        self.assertNotIn('Merge topic', [c.subject for c in commits])

    def test_base_checks_base_to_head_when_the_ref_exists_otherwise_the_last_commit(self):
        self.commit('chore: base\n\nBase.\n')
        git(self.repo, 'branch', 'base')
        self.commit('fix: bad\n\nWhy.\n\nClaude-Session: https://claude.ai/s/1\n')
        self.commit('feat: fine\n\nWhy.\n')
        code, out, _ = self.run_main('--base', 'base')
        self.assertEqual(code, 1, 'the range base..HEAD includes the bad commit, not only the last one')
        self.assertIn('fix: bad', out)
        code, out, _ = self.run_main('--base', 'origin/missing')
        self.assertEqual((code, out), (0, 'commit-message check: OK: 1 commit checked\n'))

    def test_base_that_is_head_checks_the_last_commit(self):
        self.commit('feat: one\n\nWhy.\n')
        self.assertEqual(self.run_main('--base', 'HEAD')[1], 'commit-message check: OK: 1 commit checked\n')

    def test_an_unreadable_range_is_an_error_not_a_pass(self):
        self.commit('feat: one\n\nWhy.\n')
        code, _, err = self.run_main('--range', 'nosuchbase..HEAD')
        self.assertEqual(code, 1)
        self.assertIn('commit-message check: ERROR', err)

    def test_log_parsing_keeps_multiline_messages_whole(self):
        text = (f'abc1234{check.FIELD}subject one{check.FIELD}subject one\n\nline a\nline b\n{check.RECORD}\n'
                f'def5678{check.FIELD}subject two{check.FIELD}subject two\n{check.RECORD}')
        commits = check.parse_log(text)
        self.assertEqual([(c.short_sha, c.subject) for c in commits], [('abc1234', 'subject one'), ('def5678', 'subject two')])
        self.assertIn('line b', commits[0].message)


if __name__ == '__main__':
    unittest.main()
