import json,hashlib
from pathlib import Path
r=Path(__file__).resolve().parents[1]; m=json.loads((r/'evidence/chunk-manifest.json').read_text(encoding='utf-8'))
pre={k:True for k in ['skill_read','required_references_read','helper_help_read','runtime_profile_resolved','traversal_plan_ready']}
events=[{'type':'plan_written'},{'type':'execution_started'},{'type':'node_passed','node':'acquire'},{'type':'node_passed','node':'extract'}]
run={'runtime_profile':'standalone','source':dict(m['source'],local_path=m['source']['path'],authority='primary',identity_verified=True),'fidelity':{'preserved':True,'substitutions':[]},'preflight':pre,'plan':{'path':'plan.md','nodes':['acquire','extract','traverse','requirements','verify']},'chunking':{'manifest':'evidence/chunk-manifest.json','manifest_sha256':hashlib.sha256((r/'evidence/chunk-manifest.json').read_bytes()).hexdigest(),'evidence_ledger':'evidence/chunk-evidence.json','traversal_report':'deliverables/TRAVERSAL_REPORT.md'},'deliverable':{'requested':'Complete protocol requirements and dependency map','provided':True,'paths':['deliverables/REQUIREMENTS.md'],'traversal_report':'deliverables/TRAVERSAL_REPORT.md'},'qa':{'required':['markdown-structure'],'passed':['markdown-structure']},'evidence':{'plan_status':'plan.md','skill_preflight':'evidence/skill-preflight.md','source_manifest':'evidence/source-manifest.md','chunk_ledger':'evidence/chunk-evidence.json','failure_ledger':'evidence/failure-ledger.md','verification_log':'evidence/verification-log.txt','format_qa':'evidence/format-qa.md','traversal_report':'deliverables/TRAVERSAL_REPORT.md'},'events':events}
(r/'run.json').write_text(json.dumps(run,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(r/'evidence/skill-preflight.md').write_text('# Preflight\nStandalone document-run; repository lifecycle not applicable.\n'+json.dumps(pre,indent=2)+'\nRoot skill, phase modules, all required references, run-workspace, lengthy-markdown, and current extractor/report/verifier help read. Written plan existed first. Guidance reads were bounded where output truncation affected inspection.\n',encoding='utf-8')
(r/'evidence/source-manifest.md').write_text('# Source identity\nUser-approved primary product requirements, architecture v0.2.0 / Protocol v1, dated 2026-09-17. Original remains unchanged.\n'+json.dumps(m['source'],ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(r/'evidence/failure-ledger.md').write_text('# Observed boundaries\nManifest display exceeded output budget; bounded content reads recovered complete visibility. Python display failed with UnicodeEncodeError under cp1252; UTF-8 display recovered without source transformation. Diagnosis was made from exact errors before retry, but recording was retrospective; no claim that these display attempts were successful. No required unresolved extraction or evidence node remains.\n',encoding='utf-8')
(r/'evidence/format-qa.md').write_text('# Markdown structural QA\nBundled AST block extraction emitted 107 ordinal chunks. All fenced code blocks and examples inspected in full; heading paths preserved. Atomic code fences include Unicode architecture diagrams. No dropped source sections: all numbered sections 1–21 inspected. No browser-render or advanced layout claims.\n',encoding='utf-8')
print('Initialized canonical run evidence')
