"""Check commit messages for agent and process signatures. Stdlib only.

Commit history in this repository tells the product story: what changed in
Font Kit Studio and why (see CONTRIBUTING.md). It must not carry session links,
AI co-author trailers or "Generated with" banners. This check reads every
commit in a range and fails when one does, so the rule is enforced by CI
rather than remembered.

    python scripts/dev/check_commit_messages.py                       # the last commit
    python scripts/dev/check_commit_messages.py --range origin/main..HEAD
    python scripts/dev/check_commit_messages.py --message-file .git/COMMIT_EDITMSG  # a commit-msg hook

Rejected:
  * a `*-Session:` trailer (for example `Claude-Session:`) whose value holds a
    URL or a `session_<id>`, or whose name names an AI tool;
  * a `Co-authored-by:` trailer whose email is an AI vendor's domain or the
    Copilot identity, or whose whole name is an assistant ("Claude", "Copilot");
    ordinary human co-authors are fine, including people named Claude or Devin;
  * a line starting "Generated with" or "Generated by" that names an AI tool as
    a whole word or contains a claude.ai / anthropic URL.

`--message-file PATH` checks the text git is about to commit, before the commit
exists, with the same rules, on every line: `git commit -m` and `-F` keep `#`
lines in the stored message, so a commented-out signature is refused too.

Output: `FAIL <short sha> <subject>: <reason>` per problem and a one-line
summary (`FAIL message: <reason>` for `--message-file`). Exit 0 when clean, 1 on
any failure or when git cannot read the range or the file.
Merge commits are skipped: a pull request's synthetic merge commit is not
authored text.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

#: Email domains that belong to an AI assistant. A co-author is judged by its
#: address first: a human can share a first name with an assistant ("Claude
#: Monet") or work at a company whose domain merely contains a tool's name
#: ("geminitech.com"), but nobody co-authors from the vendor's own domain. A
#: domain matches itself and its subdomains, never a look-alike.
AI_DOMAINS = (
    "anthropic.com",
    "openai.com",
    "cursor.com",
    "cursor.sh",
)

#: Exact assistant identities, compared after trimming and lower-casing the
#: whole display name. "Claude" is an assistant; "Claude Monet" is not. Model
#: suffixes ("Claude Opus 4.1", "Gemini 2.5 Pro") are covered by AI_MODEL_NAME.
AI_NAMES = (
    "claude",
    "claude code",
    "copilot",
    "github copilot",
    "chatgpt",
    "gemini",
    "codex",
    "openai codex",
    "cursor",
    "cursor agent",
    "devin",
    "aider",
)

#: An assistant's name followed by a model or product word, e.g. "Claude Sonnet 5.5".
#: A version number matches on its first digit; a word must not run on into
#: more letters, so "Claude Proctor" and "Gemini Haikuson" are people, not "pro"
#: and "haiku", while a glued digit ("Claude Opus4.1") still counts.
AI_MODEL_NAME = re.compile(
    r"^(claude|gemini|gpt|chatgpt)[ -]+(?:\d|(?:opus|sonnet|haiku|code|pro|flash|ultra|turbo)(?![a-z]))", re.IGNORECASE
)

#: Tools a "Generated with/by" banner may name, matched as whole words so
#: "Aiderman" and "cursorial-lint" pass. One list for banners and session trailers.
AI_TOOLS = (
    "claude", "claude code", "anthropic", "copilot", "chatgpt", "openai", "gpt-4", "gpt-5", "gemini",
    "cursor", "codex", "aider", "devin",
)
AI_TOOL = re.compile(r"(?<![\w-])(?:" + "|".join(re.escape(tool) for tool in AI_TOOLS) + r")(?![\w-])", re.IGNORECASE)

#: A claude.ai or anthropic URL anywhere in a "Generated" line is a signature
#: even when the tool's name is spelled some other way.
AI_URL = re.compile(r"https?://[^\s)]*(claude\.ai|anthropic\.com)", re.IGNORECASE)

URL = re.compile(r"https?://|\bclaude\.ai\b", re.IGNORECASE)
#: A session identifier on its own, such as `session_01WeZik6...`.
SESSION_ID = re.compile(r"\bsession_[A-Za-z0-9]+")
SESSION_TRAILER = re.compile(r"^\s*([A-Za-z][\w-]*-Session)\s*:\s*(.*)$", re.IGNORECASE)
CO_AUTHOR = re.compile(r"^\s*co-authored-by\s*:\s*(.*)$", re.IGNORECASE)
# `\W*` lets an emoji or markdown bullet precede the words ("\U0001F916 Generated with ...").
GENERATED = re.compile(r"^\W*generated\s+(?:with|by)\b(.*)$", re.IGNORECASE)
IDENTITY = re.compile(r"^\s*(?P<name>[^<]*?)\s*(?:<(?P<email>[^>]*)>)?\s*$")

#: Separators that cannot appear in a commit message, for parsing `git log`.
FIELD = "\x1f"
RECORD = "\x1e"
ZERO_SHA = re.compile(r"^0+$")


@dataclass(frozen=True)
class Commit:
    """One commit: its abbreviated hash, subject line and full message."""

    short_sha: str
    subject: str
    message: str


def is_ai_identity(name: str, email: str) -> bool:
    """True when a name and email identify an AI assistant, and not merely resemble one.

    The email is judged first, by exact domain (or subdomain). The Copilot
    identity is GitHub's own noreply or github.com address with "copilot" as
    the whole local part (or its `<id>+Copilot` form). A name counts only as
    an exact assistant identity, so ordinary people keep their trailers.
    """
    address = email.strip().lower()
    local, _, domain = address.rpartition("@")
    if any(domain == known or domain.endswith("." + known) for known in AI_DOMAINS):
        return True
    if domain in ("users.noreply.github.com", "github.com") and local.split("+")[-1] == "copilot":
        return True
    cleaned = " ".join(name.split()).lower()
    return cleaned in AI_NAMES or bool(AI_MODEL_NAME.match(cleaned))


def check_message(message: str) -> list[str]:
    """Return one reason per forbidden line in a commit message; empty when clean.

    Line by line, so a message that breaks two rules reports both and the
    author can fix them in one amend.
    """
    reasons = []
    for line in message.splitlines():
        session = SESSION_TRAILER.match(line)
        session_name = session.group(1).replace("-", " ") if session else ""
        if session and (
            URL.search(session.group(2)) or SESSION_ID.search(session.group(2)) or AI_TOOL.search(session_name)
        ):
            reasons.append(f"session identifier in trailer: {line.strip()}")
            continue
        co_author = CO_AUTHOR.match(line)
        if co_author:
            identity = IDENTITY.match(co_author.group(1))
            if identity and is_ai_identity(identity.group("name"), identity.group("email") or ""):
                reasons.append(f"AI assistant co-author: {line.strip()}")
            continue
        generated = GENERATED.match(line)
        if generated and (AI_TOOL.search(generated.group(1)) or AI_URL.search(generated.group(1))):
            reasons.append(f"AI generation banner: {line.strip()}")
    return reasons


def parse_log(text: str) -> list[Commit]:
    """Parse the output of `git log --format=%h<FS>%s<FS>%B<RS>` into commits."""
    commits = []
    for record in text.split(RECORD):
        if not record.strip():
            continue
        short_sha, subject, message = record.lstrip("\n").split(FIELD, 2)
        commits.append(Commit(short_sha, subject, message))
    return commits


class GitError(RuntimeError):
    """git could not read the requested range."""


def _git(repo: Path, *args: str) -> str:
    """Run git in `repo` and return stdout, or raise GitError with git's own message."""
    result = subprocess.run(
        ["git", *args], cwd=repo, capture_output=True, text=True, encoding="utf-8", check=False
    )
    if result.returncode:
        raise GitError(result.stderr.strip() or f"git {' '.join(args)} failed")
    return result.stdout


def commits_in_range(range_spec: str | None, repo: Path) -> list[Commit]:
    """The non-merge commits in `range_spec`, or just the last commit when none is given.

    A push to a new branch reports an all-zero "before" sha, which is not a
    revision; that case means "the last commit" too, not an error.
    """
    log_format = f"--format=%h{FIELD}%s{FIELD}%B{RECORD}"
    if not range_spec or ZERO_SHA.match(range_spec.split("..", 1)[0]):
        return parse_log(_git(repo, "log", "-1", "--no-merges", log_format, "HEAD"))
    return parse_log(_git(repo, "log", "--no-merges", log_format, range_spec))


def base_range(base: str, repo: Path) -> str | None:
    """`base..HEAD` when `base` exists and is not HEAD itself, otherwise None (the last commit).

    For a manual run: check everything the branch adds over `origin/main`
    when that is available, and fall back to the last commit when it is not
    (a shallow clone, or a run on the base branch itself).
    """
    try:
        base_sha = _git(repo, "rev-parse", "--verify", "--quiet", f"{base}^{{commit}}").strip()
        head_sha = _git(repo, "rev-parse", "HEAD").strip()
    except GitError:
        return None
    return None if base_sha == head_sha else f"{base}..HEAD"


def failures_for(commits: list[Commit]) -> list[str]:
    """Format every reason for every commit as `FAIL <short sha> <subject>: <reason>`."""
    return [
        f"FAIL {commit.short_sha} {commit.subject}: {reason}"
        for commit in commits
        for reason in check_message(commit.message)
    ]


def check_message_file(path: Path) -> int:
    """Check every line of the commit message in `path`; return the exit code."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError as error:
        print(f"commit-message check: ERROR: {error}", file=sys.stderr)
        return 1
    # `git commit -v` appends the staged diff below this line, and git drops everything
    # from it on before it stores the message, so the diff is not part of the message.
    text = text.split("\n# ------------------------ >8 ------------------------\n", 1)[0]
    reasons = check_message(text)
    for reason in reasons:
        print(f"FAIL message: {reason}")
    if reasons:
        print("commit-message check: FAIL: the message carries agent or process signatures")
        return 1
    print("commit-message check: OK: message checked")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Check the range, print each failure and a one-line summary; return the exit code."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--range", dest="range_spec", default=None, help="git revision range (default: the last commit)")
    parser.add_argument("--base", default=None,
                        help="when --range is not given: check BASE..HEAD if BASE exists, else the last commit")
    parser.add_argument("--repo", type=Path, default=Path.cwd(), help="repository to read (default: the current directory)")
    parser.add_argument("--message-file", type=Path, default=None,
                        help="check the commit message in this file (for a commit-msg hook); not with --range or --base")
    args = parser.parse_args(argv)
    if args.message_file is not None:
        if args.range_spec is not None or args.base is not None:
            parser.error("--message-file cannot be combined with --range or --base")
        return check_message_file(args.message_file)
    try:
        range_spec = args.range_spec
        if range_spec is None and args.base:
            range_spec = base_range(args.base, args.repo)
        commits = commits_in_range(range_spec, args.repo)
    except (GitError, FileNotFoundError) as error:
        print(f"commit-message check: ERROR: {error}", file=sys.stderr)
        return 1
    failures = failures_for(commits)
    for line in failures:
        print(line)
    bad = len({line.split(" ", 2)[1] for line in failures})
    noun = "commit" if len(commits) == 1 else "commits"
    if failures:
        print(f"commit-message check: FAIL: {bad} of {len(commits)} {noun} carry agent or process signatures")
        return 1
    print(f"commit-message check: OK: {len(commits)} {noun} checked")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
